services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT""
    envVars:
      - key: IMGBB_API_KEY
        sync: false